config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  post '/groups/:name/:icon', to: 'groups#default_group', as: :default_group
  resources :users, only: [:show] do
    resources :groups do
      resources :entities 
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :manage, Group, user: user
    can :manage, Entity, user:
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  # order by created_at DESC
  default_scope { order(created_at: :desc) }
  after_initialize :init

  belongs_to :user
  belongs_to :group

  validates :name, :amount, presence: true
  validates :amount, numericality: { greater_than: 0 }

  def init
    self.amount ||= 1
  end
end

app/models/group.rb
class Group < ApplicationRecord
  mount_uploader :icon, IconUploader

  belongs_to :user
  has_many :entities, dependent: :destroy

  validates :name, presence: true

  def self.icons
    {
      communication: 'communication.png',
      education: 'education.png',
      entertaiment: 'entertaiment.png',
      food: 'food.png',
      healthcare: 'healthcare.png',
      housing: 'housing.png',
      internet: 'internet.png',
      investment: 'investment.png',
      default: 'default.png'
    }
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :groups, dependent: :destroy
  has_many :entities, through: :groups

  validates :name, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: %i[home]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    user_groups_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[email password password_confirmation name])
    devise_parameter_sanitizer.permit(:sign_in, keys: %i[email password])
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  def index
    @group = Group.find(params[:group_id])
    @entities = current_user.entities
  end

  def new
    @group = Group.find(params[:group_id])
  end

  def create
    @group = Group.find(params[:group_id])
    @entity = @group.entities.build(entity_params)
    @entity.user = current_user
    if @entity.save
      flash[:notice] = 'Entity created successfully'
      redirect_to user_group_entities_path(current_user.id, @group.id)
    else
      flash[:alert] = 'Entity not created'
      render :new
    end
  end

  def destroy
    @group = Group.find(params[:group_id])
    @entity = Entity.find(params[:id])
    @entity.destroy
    redirect_to user_group_entities_path(current_user, @group)
  end

  private

  def entity_params
    params.require(:entity).permit(:name, :amount)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = current_user.groups.includes(:entities).all
  end

  def new
    @icons = Group.icons
  end

  def create
    @group = current_user.groups.new(group_params)
    if @group.save
      redirect_to user_groups_path(current_user.id)
    else
      render :new
    end
  end

  def show
    @group = Group.find(params[:id])
    @entities = @group.entities
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      flash[:notice] = 'Group updated successfully'
      redirect_to user_groups_path(current_user.id)
    else
      render :edit
    end
  end

  def default_group
    name = params[:name]
    icon = params[:icon] + params[:format]
    # mount image with carrierwave
    @group = current_user.groups.new(name:, icon:)
    if @group.save
      redirect_to user_groups_path(current_user.id)
    else
      render :new
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to user_groups_path(current_user.id)
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon, :icon_cache)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def ressource_link(current_path)
    r = { name: '', link: '' }
    if current_path == new_user_registration_path
      r[:name] = 'login'
      r[:link] = new_user_session_path
    elsif current_path == new_user_session_path
      r[:name] = 'Sign up'
      r[:link] = new_user_registration_path
    end
  end
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
  def default_group_icon(name)
    icon = Group.icons[name.to_sym]
    return icon unless icon.nil?

    Group.icons[:default]
  end
end

app/views/entities/_form.html.erb
<%= form_with model:[current_user, @group, @group.entities.build] , local: true do |form|%>
    <%= form.text_field :name, placeholder:"transaction name", class:"form_control"  %>
    <%= form.number_field :amount, placeholder:"transaction amount", class:"form_control"  %>
    <%= form.submit %>
<% end %>

app/views/entities/index.html.erb
<%= render 'groups/group_nav'%>
<h5 class="text-center mt-4">Total spend for <%= @group.name %> : $<%= @group.entities.sum(:amount) %></h5>
<div class="container">
  <table class="table table-striped", style="text-align: center;">
    <thead>
      <tr>
        <th>Date</th>
        <th>Name</th>
        <th>Amount</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% if @group.entities.empty?%>
            <p class="text-center text-primary"> No transaction yet ! </p>
      <% else %>
      
        <% @group.entities.each do |t| %>
            <tr>
            <td><%= t.created_at.strftime("%d-%b-%Y") %></td>
            <td><%= t.name %></td>
            <td>$<%= t.amount %></td>
            <td>        
                <%= button_to "delete", user_group_entity_path(current_user, t.group, t ), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-sm btn-success mb-5" %>
            </td>
            </tr>
        <% end %>
    <% end %>
    </tbody>
  </table>
</div>
<button type="button" class="btn action-btn" data-toggle="modal" data-target="#exampleModalCenter">New transaction</button>
<div class="btn-border"></div>

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Add transaction for <%=@group.name%></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render "entities/form"%>
      </div>
    </div>
  </div>
</div>

app/views/entities/new.html.erb
<h1>Entities#new</h1>
<%= form_with model:[current_user, @group, @group.entities.build] , local: true do |form|%>
    <%= form.label :name %>
    <%= form.text_field :name %>
    <%= form.label :amount %>
    <%= form.number_field :amount %>
    <%= form.submit %>
<% end %>

app/views/groups/_group_nav.html.erb
<div class="pos-f-t">
  <% if user_signed_in? %>
    <div class="collapse" id="navbarToggleExternalContent">
      <div class="bg-ligth p-4">
        <h4 class="text-dark">Hi <%= current_user.name %></h4>
      </div>
    </div>
  <% else %>
    <div class="collapse" id="navbarToggleExternalContent">
      <div class="bg-ligth p-4">
        <h4 class="text-dark">Flooz</h4>
        <span class="text-muted">Manage better your money !</span>
      </div>
    </div>
  <% end %>
  <nav class="navbar navbar-dark bg-blue">
    <%= button_to "<BACK", user_groups_path(current_user), method: :get, class:"btn-bold" %>
    <%= button_to "LOGOUT", destroy_user_session_path, method: :delete, class:"btn-bold" %>
  </nav>
</div>

app/views/groups/edit.html.erb
<%= form_for [current_user, @group], local: true do |form|%>
    <%= form.text_field :icon, placeholder:"groupe icone"%>
    <%= form.label :name %>
    <%= form.text_field :name %>
    <%= form.submit %>
<% end %>

app/views/groups/index.html.erb
<%= render 'sheared/nav_bar'%>
<div class="container d-flex flex-column justify-content-center align-items-center mt-2 p-2">
    <% @groups.each do |g|%>
    <div class="card d-flex flex-row m-1 p-1" style="width: 100%">
        <div>
            <span class="material-symbols-outlined img">
                <%if g.icon.url.nil?%>
                    <%= image_tag default_group_icon(g.name), style:"width: 80px;" %>
                <% else %>
                    <%=image_tag g.icon.url, class:"img-fluid", style:"width: 80px;" %>
                <% end %>
            </span>
        </div>
    
        <div class="card-body d-flex flex-column justify-content-center align-items-right">
            <%= link_to(user_group_entities_path(current_user, g)) do %>
                <h5><%= g.name.upcase %></h5>
                <div class="separate-line"></div>
                <%= g.created_at.strftime("%d-%b-%Y")  %>
            <% end %>
        </div>
        <div class="d-flex flex-row justify-content-center align-items-center m-2">
                <h4 class="card-text text-muted">$<%= g.entities.sum(:amount) %></h4>
        </div>
    </div>
<% end %>
</div>
<%= link_to 'New Group', new_user_group_path, class: "btn action-btn" %>
<div class="btn-border"></div>

app/views/groups/new.html.erb
<%= render 'group_nav'%>
<div class="container">
    <div class="separation"></div>
    <h5 class="text-center text-muted mb-2"> Add custom group </h5>
    <div class="group_form">
        <%= form_with model:[current_user, current_user.groups.build] , local: true do |form|%>
            <%= form.text_field :name, required: true, placeholder:"Group name"%>
            <%= form.file_field :icon, required: true%>
            <%= form.submit class:"btn btn-sm btn-success"  %>
        <% end %>
    </div>
    <hr />
    <div class="separation"></div>
    <h5 class="text-center text-muted"> Or select defaut group </h5>
    <div class="container d-flex mt-3 p-3 default_group">
        <% @icons.map do |name, icon| %>
            <div class="col-sm-2 col-sm-3 padding:10px;">
                <%= image_tag icon, style:"width: 100px;"%>
                <%= name %>
                <%=button_to "Add", default_group_path(name, icon), method: :post, class:"btn btn-sm btn-success" %> 
            </div>
        <% end%>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flooz</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <div class="flash">
      <% flash.each do |name, message| %>
            <div class="alert alert-<%=name%>" role="alert">
                  <%= message %>
            </div>
      <% end %>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/home.html.erb
<div class="pos-f-t">
  <% if user_signed_in? %>
    <div class="collapse" id="navbarToggleExternalContent">
      <div class="bg-ligth p-4">
        <h4 class="text-dark">Hi <%= current_user.name %></h4>
      </div>
    </div>
  <% else %>
    <div class="collapse" id="navbarToggleExternalContent">
      <div class="bg-ligth p-4">
        <h4 class="text-dark">Flooz</h4>
        <span class="text-muted">Manage better your money !</span>
      </div>
    </div>
  <% end %>
  <nav class="navbar navbar-dark bg-blue">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <% if user_signed_in?%>
      <%= button_to "LOGOUT", destroy_user_session_path, method: :post, class:"btn-bold" %>
    <% end %>
  </nav>
</div>
<main class="splash">
    <div class="lead text-center">
      <h1 class="h1">Flooz</h1>
      <em class="lead text-indigo"><small>Manage better your money !</small></em>
    </div>
      <% if user_signed_in?%>
        <%= link_to "My transactions", user_groups_path(current_user),  class:"btn btn-bold"%>
      <%else%>
        <div class="actions">
          <%= link_to "SIGN IN", new_user_session_path, class:"btn btn-bold"%>
          <%= link_to "SIGN UP", new_user_registration_path, class:"btn btn-muted" %>
        </div>
      <% end %>
</main>

app/views/sheared/_nav_bar.html.erb
<div class="pos-f-t">
  <% if user_signed_in? %>
    <div class="collapse" id="navbarToggleExternalContent">
      <div class="bg-ligth p-4">
        <h4 class="text-dark">Hi <%= current_user.name %></h4>
      </div>
    </div>
  <% else %>
    <div class="collapse" id="navbarToggleExternalContent">
      <div class="bg-ligth p-4">
        <h4 class="text-dark">Flooz</h4>
        <span class="text-muted">Manage better your money !</span>
      </div>
    </div>
  <% end %>
  <nav class="navbar navbar-dark bg-blue">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <%= button_to "LOGOUT", destroy_user_session_path, method: :delete, class:"btn-bold" %>
  </nav>
</div>